In [ ]:
import requests
import pandas as pd
import json
from datetime import datetime
import logging

# Configure the logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

force_none_proxies = {
    "http": None,
    "https": None,
}

import hashlib


def get_md5_encoded_string(phone_number, date, word):
    # Concatenate the input values
    input_string = f"{phone_number}{date}{word}"

    # Encode the string to bytes
    input_bytes = input_string.encode("utf-8")

    # Generate the MD5 hash
    md5_hash = hashlib.md5(input_bytes)

    # Convert the hash to its hexadecimal representation
    md5_hex = md5_hash.hexdigest()

    return md5_hex


# Example usage
phone_number = "18618107293"
date = datetime.now().strftime("%Y%m%d")
word = "login"
md5_encoded_string = get_md5_encoded_string(phone_number, date, word)
logging.info(md5_encoded_string)


def get_token_for_env(env="https://h5.summerfarm.net"):
    url = f"{env}/openid?phone={phone_number}&sign={md5_encoded_string}"
    logging.info(url)
    token = requests.get(url=url, timeout=12000, proxies=force_none_proxies)
    logging.info(f"token.status_code:{token.status_code}, text:{token.text}")
    try:
        token = json.loads(token.text)
        logging.info(f"{token}")
        return {"env": f"{env}", "token": token["data"]["token"]}
    except Exception as e:
        logging.error(f"获取Token失败:{url}, {token}, {e}")
        raise e
    

token_of_h5=get_token_for_env('https://dev2h5.summerfarm.net')

In [ ]:
from sls_client import get_sls_data_by_query
from datetime import datetime, timedelta

to_time = datetime.now()- timedelta(days=0)
from_time = datetime.now() - timedelta(hours=1)

query = """ap:/price/query/take-actual-price and phone:18618107293
|select distinct json_extract(json_extract_scalar(ai, '$.data'),'$.orderNow[0]') data_orderNow
from log"""
sku_object_list_from_sls = get_sls_data_by_query(
    from_time=from_time,
    to_time=to_time,
    query=query,
    project="xianmu-front-end-log",
    logstore="fe-test",
)

sku_object_list_from_sls.head(2)

In [ ]:
import json
sku_object_list = []
for index, row in sku_object_list_from_sls.iterrows():
    sku_object_list.append(json.loads(row['data_orderNow']))

print(len(sku_object_list), sku_object_list[0])

## 开始做验证

In [ ]:
sku_result={}

host_name = "dev2h5.summerfarm.net"

for selected_skus in sku_object_list:
    sku_id = selected_skus['sku']
    data_to_send = {
        "orderNow": selected_skus,
        "minLadderPrice": 1,
    }
    print(data_to_send)
    started_at = datetime.now()

    # Send request and measure upload time
    upload_start = datetime.now()
    response = requests.post(
        f"https://{host_name}/price/query/take-actual-price",
        headers={"token": token_of_h5["token"]},
        json=data_to_send,
    )
    response_json = response.json()
    print(response_json)
    sku_result[sku_id]=response_json['data'][0] if len(response_json['data'])>0 else None

In [40]:
import random

# Randomly select 20 elements from sku_object_list

time_cost_list = []
for index in range(0, 1000):  # len(my_list) * 5
    cost_of_this_run = {}
    for sku_item_cnt in [1, 6, 12, 20]:
        selected_skus = random.sample(sku_object_list, sku_item_cnt)
        data_to_send = {
            "orderNow": selected_skus,
            "minLadderPrice": 1,
        }
        started_at = datetime.now()

        # Send request and measure upload time
        upload_start = datetime.now()
        response = requests.post(
            f"https://{host_name}/price/query/take-actual-price",
            headers={"token": token_of_h5["token"]},
            json=data_to_send,
        )
        response_json = response.json()
        end_time = datetime.now()
        has_data = (
            isinstance(response_json["data"], list) and len(response_json["data"]) > 0
        )
        if has_data:
            for result in response_json["data"]:
                sku = result["sku"]
                takeActualPrice = result["takeActualPrice"]
                is_all_correct = (
                    sku_result.get(sku, {}).get("takeActualPrice") == takeActualPrice
                )
                if not is_all_correct:
                    logging.error(
                        f"结果不对！！！selected_skus:{selected_skus}, \nresult:{result}"
                    )

        rt = int((end_time - started_at).total_seconds() * 1000)
        server_rt = int(response.headers["x-server-time-cost"])
        cost_of_this_run[f"rt_{sku_item_cnt}"] = server_rt
        cost_of_this_run[f"total_rt_{sku_item_cnt}"] = rt
        if has_data:
            cost_of_this_run[f"has_data_rt_{sku_item_cnt}"] = server_rt
        else:
            cost_of_this_run[f"no_data_rt_{sku_item_cnt}"] = server_rt

    time_cost_list.append(cost_of_this_run)

time_cost_list_df = pd.DataFrame(time_cost_list)

In [41]:
time_cost_list_df.describe()

,rt_1,total_rt_1,has_data_rt_1,rt_6,total_rt_6,has_data_rt_6,rt_12,total_rt_12,has_data_rt_12,rt_20,total_rt_20,has_data_rt_20,no_data_rt_1,no_data_rt_6,no_data_rt_12,no_data_rt_20
count,1000.000000,1000.000000,149.000000,1000.000000,1000.000000,700.000000,1000.000000,1000.000000,921.000000,1000.00000,1000.000000,998.000000,851.000000,300.000000,79.000000,2.000000
mean,27.635000,249.708000,37.261745,41.816000,263.927000,46.460000,59.004000,282.860000,60.922910,88.86000,312.113000,88.962926,25.949471,30.980000,36.632911,37.500000
std,7.857195,57.151159,14.019001,11.510545,53.595187,10.188206,15.736506,57.776141,14.818669,20.21195,53.275891,20.098644,4.387258,5.631338,5.588856,9.192388
min,19.000000,184.000000,27.000000,22.000000,190.000000,30.000000,24.000000,196.000000,33.000000,31.00000,202.000000,43.000000,19.000000,22.000000,24.000000,31.000000
25%,24.000000,212.000000,33.000000,34.000000,228.000000,39.000000,47.000000,244.000000,50.000000,75.00000,273.000000,75.000000,23.000000,27.000000,33.000000,34.250000
50%,25.000000,231.000000,35.000000,40.000000,246.000000,44.000000,57.000000,267.000000,59.000000,87.00000,297.000000,87.000000,25.000000,31.000000,37.000000,37.500000
75%,30.000000,268.250000,38.000000,48.000000,285.250000,52.000000,70.000000,315.000000,70.000000,101.00000,339.000000,101.000000,27.000000,34.000000,40.000000,40.750000
max,194.000000,978.000000,194.000000,95.000000,622.000000,95.000000,140.000000,951.000000,140.000000,186.00000,583.000000,186.000000,58.000000,68.000000,52.000000,44.000000

In [42]:
time_cost_list_df[
    [
        "rt_1",
        "has_data_rt_1",
        "rt_6",
        "has_data_rt_6",
        "rt_12",
        "has_data_rt_12",
        "rt_20",
        "has_data_rt_20",
        "no_data_rt_1",
        "no_data_rt_6",
        "no_data_rt_12",
    ]
].quantile([0.05, 0.25, 0.5, 0.75, 0.90, 0.95, 0.99, 0.995])

,rt_1,has_data_rt_1,rt_6,has_data_rt_6,rt_12,has_data_rt_12,rt_20,has_data_rt_20,no_data_rt_1,no_data_rt_6,no_data_rt_12
0.050,22.000,31.00,25.000,34.000,36.000,41.0,60.00,60.00,22.0,24.000,26.00
0.250,24.000,33.00,34.000,39.000,47.000,50.0,75.00,75.00,23.0,27.000,33.00
0.500,25.000,35.00,40.000,44.000,57.000,59.0,87.00,87.00,25.0,31.000,37.00
0.750,30.000,38.00,48.000,52.000,70.000,70.0,101.00,101.00,27.0,34.000,40.00
0.900,35.000,42.00,56.000,59.000,79.000,80.0,115.10,115.30,30.0,36.000,44.00
0.950,38.000,46.80,63.000,66.050,86.000,87.0,125.00,125.00,33.0,39.000,45.10
0.990,53.000,62.84,78.010,80.000,101.010,101.8,143.04,143.12,43.0,54.010,48.10
0.995,55.005,102.98,80.005,81.505,106.025,108.0,150.00,150.00,54.5,57.525,50.05